#! /bin/sh

/bin/mount -a

cd /dev/

mknod -m 660 console c 5 1
mknod -m 660 null c 1 3
mknod -m 660 urandom c 1 9
mknod -m 660 random c 1 8

echo "/sbin/mdev">/proc/sys/kernel/hotplug
mdev -s

iscsid
modprobe sd_mod
modprobe vmw_pvscsi
modprobe iscsi_tcp
modprobe loop max_loop=10
mount -t debugfs nodev /sys/kernel/debug
